---
title: "ENOE Survey Questionnaires"
output:
  github_document:
    html_preview: no
    toc: no
    toc_depth: 3
editor_options:
  markdown:
    wrap: 72
knit: (function(input, ...) { rmarkdown::render( input, output_dir = here::here("Support/Country Survey Details/MEX/ENOE"), envir = globalenv() ) })
---

# The different versions of the ENOE

In the past fifteen years, the Mexican national statistics institute
(INEGI) published five versions of the labor force questionnaire or
ENOE. The ENOE has two versions: the extended version and the shorter
version. Every quarter, the INEGI conducts labor surveys using either
version.

In addition, INEGI periodically updates each questionnaire version. The
fact that there is no unique questionnaire for the entire year
introduces seasonality in the input, which could impact the process of
data analysis for the user.

## Absent Topics

After analyzing the questionnaire versions, the team concluded that
using quarter one data reduces seasonality because INEGI collected
quarter one data across the years using the extended version. The only
exception is quarter one data for years 2007 and 2008.

In table 1. the team summarized the list of absent topics in the
extended and the short questionnaire versions.

| Extended Version                                                                               | Short Version                                                                                                                    |
|------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| Questions about situation after losing a job and the length of unemployment or job inactivity. | Questions about migration and additional labor opportunities (second job).                                                       |
|                                                                                                | Questions on financial, social and economic support such as syndicate enrollment, public social welfare benefits, and insurance. |

--- [Author made. based on ENOE
Questionnaires](https://www.inegi.org.mx/programas/enoe/15ymas/)

## Type of survey questionnaires

The INEGI started using ENOE in 2005. For quarter one, INEGI introduced
five revisions of the extended version and two for the shorter version
of the questionnaire.

Table 2. ENOE questionnaire revision by year

| Year         | Version Q1              |
|--------------|-------------------------|
| 2005 to 2006 | [First Extended Version](https://www.inegi.org.mx/contenidos/programas/enoe/15ymas/doc/c_amp_v1.pdf)  |
| 2007         | [First Short Version](https://www.inegi.org.mx/contenidos/programas/enoe/15ymas/doc/c_bas_v1.pdf)     |
| 2008         | [Second Short Version](https://www.inegi.org.mx/contenidos/programas/enoe/15ymas/doc/c_bas_v2.pdf)    |
| 2009         | [Second Extended Version](https://www.inegi.org.mx/contenidos/programas/enoe/15ymas/doc/c_amp_v2.pdf) |
| 2010 to 2012 | [Third Extended Version](https://www.inegi.org.mx/contenidos/programas/enoe/15ymas/doc/c_amp_v3.pdf) |
| 2013 to 2015 |[Fourth Extended Version](https://www.inegi.org.mx/contenidos/programas/enoe/15ymas/doc/c_bas_v4.pdf) |
| 2016 to 2020 | [Fifth Extended Version](https://www.inegi.org.mx/contenidos/programas/enoe/15ymas/doc/c_bas_v5.pdf)  |

--- [Author made. based on ENOE
Questionnaires](https://www.inegi.org.mx/programas/enoe/15ymas/)
